# ============================================
# Ambitopia [yellow]
# ============================================

format = """
[](#fdf400)\
$os\
$username\
[](bg:#17181c fg:#fdf400)\
$directory\
[](fg:#17181c bg:#2e2f32)\
$git_branch\
[█](fg:#2e2f32)\
[](fg:#2e2f32 bg:#454649)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$scala\
$haskell\
$elixir\
$erlang\
$python\
$ruby\
$perl\
$dotnet\
$swift\
$dotnet\
$swift\
$package\
[█](fg:#454649)\
[](fg:#454649 bg:#5c5d60)\
$docker_context\
$conda\
$pixi\
[█](fg:#5c5d60)\
[](fg:#5c5d60 bg:#e3e3e3)\
$time\
[ ](fg:#e3e3e3)\
$fill\
$git_status\
$line_break$character
"""

add_newline = false

palette = 'ambitopia_yellow'

[palettes.ambitopia_yellow]
color1 = '#030408'
color2 = '#17181c'
color3 = '#2e2f32'
color4 = '#454649'
color5 = '#fdf400'
color6 = '#e3e3e3'
color7 = '#c5003c'
color8 = '#397979'

[os]
disabled = false
style = "bg:#fdf400 fg:#030408"

[os.symbols]
Windows = " ⊞"
Ubuntu = " "
SUSE = " "
Raspbian = " "
Mint = " "
Macos = " "
Manjaro = " "
Linux = " 󰌽"
Gentoo = " "
Fedora = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
EndeavourOS = " "
CentOS = " "
Debian = " "
Redhat = " "
RedHatEnterprise = " "
Pop = " "


[username]
show_always = true
style_user = "bg:#fdf400 fg:#030408"
style_root = "bg:#fdf400 fg:#030408"
format = '[ $user ]($style)'

[directory]
style = "fg:#fdf400 bg:#17181c"
format = "[  $path  ]($style)"
truncation_length = 2
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
symbol = " "
style = "bg:#2e2f32"
format = '[[  $symbol $branch ](fg:#e3e3e3 bg:#2e2f32)]($style)'

[git_status]
style = "bg:#c5003c"
format = '[([](#c5003c) $all_status$ahead_behind[](fg:#c5003c))](fg:#e3e3e3 bg:#c5003c)'
ahead = "⇡$count"
behind = "⇣$count"
diverged = "⇕⇡$ahead_count⇣$behind_count"
up_to_date = ""
untracked = "?$count"
stashed = "=$count"
modified = "!$count"
staged = "+$count"
renamed = "»$count"
deleted = "✘$count"

[nodejs]
symbol = " ⬢ "
style = "bg:#454649"
format = '[[ $symbol( $version) ](fg:#e3e3e3 bg:#454649)]($style)'
disabled = true

[c]
symbol = " C "
style = "bg:#454649"
format = '[[ $symbol( $version) ](fg:#e3e3e3 bg:#454649)]($style)'

[cpp]
symbol = " C++ "
style = "bg:#454649"
format = '[[ $symbol( $version) ](fg:#e3e3e3 bg:#454649)]($style)'

[rust]
symbol = "  "
style = "bg:#454649"
format = '[[ $symbol( $version) ](fg:#e3e3e3 bg:#454649)]($style)'

[golang]
symbol = "  "
style = "bg:#454649"
format = '[[ $symbol( $version) ](fg:#e3e3e3 bg:#454649)]($style)'

[php]
symbol = "  "
style = "bg:#454649"
format = '[[ $symbol( $version) ](fg:#e3e3e3 bg:#454649)]($style)'

[java]
symbol = "  "
style = "bg:#454649"
format = '[[ $symbol( $version) ](fg:#e3e3e3 bg:#454649)]($style)'

[kotlin]
symbol = " Kotlin "
style = "bg:#454649"
format = '[[ $symbol( $version) ](fg:#e3e3e3 bg:#454649)]($style)'

[haskell]
symbol = " λ "
style = "bg:#454649"
format = '[[ $symbol( $version) ](fg:#e3e3e3 bg:#454649)]($style)'

[python]
symbol = "  "
style = "bg:#454649"
format = '[[ $symbol( $version)( \($virtualenv\)) ](fg:#e3e3e3 bg:#454649)]($style)'

[package]
symbol = "  "
style = "bg:#454649"
format = '[[ $symbol( $version) ](fg:#e3e3e3 bg:#454649)]($style)'

[swift]
symbol = " Swift "
style = "bg:#454649"
format = '[[ $symbol( $version) ](fg:#e3e3e3 bg:#454649)]($style)'

[elixir]
symbol = "  "
style = "bg:#454649"
format = '[[ $symbol( $version) ](fg:#e3e3e3 bg:#454649)]($style)'

[erlang]
symbol = " Erlang "
style = "bg:#454649"
format = '[[ $symbol( $version) ](fg:#e3e3e3 bg:#454649)]($style)'

[scala]
symbol = " Scala "
style = "bg:#454649"
format = '[[ $symbol( $version) ](fg:#e3e3e3 bg:#454649)]($style)'

[perl]
symbol = "  "
style = "bg:#454649"
format = '[[ $symbol( $version) ](fg:#e3e3e3 bg:#454649)]($style)'

[ruby]
symbol = "  "
style = "bg:#454649"
format = '[[ $symbol( $version) ](fg:#e3e3e3 bg:#454649)]($style)'

[dotnet]
symbol = " .NET "
style = "bg:#454649"
format = '[[ $symbol( $version) ](fg:#e3e3e3 bg:#454649)]($style)'

[docker_context]
symbol = "  "
style = "bg:#5c5d60"
format = '[[ $symbol( $context) ](fg:#e3e3e3 bg:#5c5d60)]($style)'

[conda]
symbol = " Conda "
style = "bg:#5c5d60"
format = '[[ $symbol( $environment) ](fg:#e3e3e3 bg:#5c5d60)]($style)'

[pixi]
symbol = " Pixi "
style = "bg:#5c5d60"
format = '[[ $symbol( $version)( $environment) ](fg:#e3e3e3 bg:#5c5d60)]($style)'

[time]
disabled = false
time_format = "%I:%M %p"
style = "bg:#e3e3e3"
format = '[[  󱑍 $time ](fg:#030408 bg:#e3e3e3)]($style)'

[line_break]
disabled = false

[fill]
symbol = " "

[character]
disabled = false
success_symbol = '[↪](bold fg:#e3e3e3)'
error_symbol = '[](bold fg:#e3e3e3)'
vimcmd_symbol = '[⮜](bold fg:#e3e3e3)'
vimcmd_replace_one_symbol = '[⮜](bold fg:#e3e3e3)'
vimcmd_replace_symbol = '[⮜](bold fg:#e3e3e3)'
vimcmd_visual_symbol = '[⮜](bold fg:#e3e3e3)'
