# ============================================
# Ambitopia [yellow]
# ============================================

# : Manager {{{

[manager]
cwd = { fg = "#fdf400" }

# Hovered
hovered = { bg = "#fdf400", fg = "#030408", bold = true }
preview_hovered = { fg = "#fdf400", bg = "#17181c" }

# Find
find_keyword  = { fg = "#fdf400", bold = true, italic = true, underline = true }
find_position = { fg = "#cd8ffe", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#7ca893", bg = "#7ca893" }
marker_cut      = { fg = "#fcad7b", bg = "#e61e5b" }
marker_marked   = { fg = "#fdf400", bg = "#55ead4" }
marker_selected = { fg = "#fdf400", bg = "#fdf400" }

# Count
count_copied   = { fg = "#030408", bg = "#7ca893" }
count_cut      = { fg = "#030408", bg = "#fcad7b" }
count_selected = { fg = "#030408", bg = "#fdf400" }

# Border
border_symbol = "│"
border_style  = { fg = "#fdf400" }

[indicator]
preview = { fg = "#030408", bg = "#fdf400" }
parent  = { fg = "#fdf400", bg = "#17181c" }
current = { fg = "#030408", bg = "#fdf400" }
padding = { open = "█", close = "█" }

# : }}}
# : Tabs {{{

[tabs]
active   = { fg = "#030408", bg = "#fdf400", bold = true }
inactive = { fg = "#fdf400", bg = "#17181c" }

# : }}}
# : Mode {{{

[mode]
normal_main = { fg = "#030408", bg = "#fdf400", bold = true }
normal_alt  = { fg = "#fdf400", bg = "#17181c" }

# Select mode
select_main = { fg = "#030408", bg = "#7ca893", bold = true }
select_alt  = { fg = "#fdf400", bg = "#17181c" }

# Unset mode
unset_main = { fg = "#030408", bg = "#cd8ffe", bold = true }
unset_alt  = { fg = "#fdf400", bg = "#17181c" }

# : }}}
# : Status bar {{{

[status]
overall = { fg = "#fdf400" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label = { fg = "#030408", bold = true }
progress_normal = { fg = "#fdf400", bg = "#17181c" }
progress_error = { fg = "#e61e5b", bg = "#17181c" }

# Permissions
perm_sep   = { fg = "#fdf400" }
perm_type  = { fg = "#7ca893" }
perm_read  = { fg = "#fcad7b" }
perm_write = { fg = "#e61e5b" }
perm_exec  = { fg = "#cd8ffe" }

# : }}}
# : Pick {{{

[pick]
border = { fg = "#fdf400" }
active = { fg = "#cd8ffe", bold = true }
inactive = {}

# : }}}
# : Input {{{

[input]
border   = { fg = "#fdf400" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}
# : Completion {{{

[completion]
border = { fg = "#fdf400" }
active = { bg = "#fdf400", fg = "#030408" }
inactive = {}

# : }}}
# : Tasks {{{

[tasks]
border  = { fg = "#fdf400" }
title   = {}
hovered = { fg = "#cd8ffe", underline = true }

# : }}}
# : Which {{{

[which]
mask            = { bg = "#17181c" }
cand            = { fg = "#7ca893" }
rest            = { fg = "#e3e3e3" }
desc            = { fg = "#cd8ffe" }
separator       = "  "
separator_style = { fg = "#55ead4" }

# : }}}
# : Help {{{

[help]
on      = { fg = "#7ca893" }
run     = { fg = "#cd8ffe" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#030408", bg = "#e3e3e3" }

# : }}}
# : Spotter {{{

[spot]
border   = { fg = "#fdf400" }
title    = { fg = "#fdf400" }
tbl_col  = { fg = "#7ca893" }
tbl_cell = { fg = "#cd8ffe", bg = "#17181c" }

# : }}}
# : Notify {{{

[notify]
title_info  = { fg = "#7ca893" }
title_warn  = { fg = "#e61e5b" }
title_error = { fg = "#fcad7b" }

icon_info  = ""
icon_warn  = ""
icon_error = ""

# : }}}
# : File-specific styles {{{

[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "#55ead4" },
	# Media
	{ mime = "video/*", fg = "#cd8ffe" },
	{ mime = "audio/*", fg = "#cd8ffe" },
	# Archives
	{ mime = "application/zip",             fg = "#fcad7b" },
	{ mime = "application/x-tar",           fg = "#fcad7b" },
	{ mime = "application/x-bzip*",         fg = "#fcad7b" },
	{ mime = "application/x-bzip2",         fg = "#fcad7b" },
	{ mime = "application/x-7z-compressed", fg = "#fcad7b" },
	{ mime = "application/x-rar",           fg = "#fcad7b" },
	{ mime = "application/x-xz",            fg = "#fcad7b" },
	# Documents
	{ mime = "application/doc",        fg = "#fcd670" },
	{ mime = "application/epub+zip",   fg = "#fcd670" },
	{ mime = "application/pdf",        fg = "#fcd670" },
	{ mime = "application/rtf",        fg = "#fcd670" },
	{ mime = "application/vnd.*",      fg = "#fcd670" },
	# Special files
	{ mime = "*", is = "orphan", fg = "#e61e5b", bg = "#17181c" },
	{ mime = "application/*exec*", fg = "#7ca893" },
	# Fallback
	{ name = "*", fg = "#e3e3e3" },
	{ name = "*/", fg = "#fdf400" },
]

# : }}}